/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateGameInput = {
  id?: string | null,
  title: string,
  description: string,
  image?: string | null,
  creatorId: string,
  categories?: Array< string > | null,
};

export type ModelGameConditionInput = {
  title?: ModelStringInput | null,
  description?: ModelStringInput | null,
  image?: ModelStringInput | null,
  creatorId?: ModelStringInput | null,
  categories?: ModelStringInput | null,
  and?: Array< ModelGameConditionInput | null > | null,
  or?: Array< ModelGameConditionInput | null > | null,
  not?: ModelGameConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type Game = {
  __typename: "Game",
  id?: string,
  title?: string,
  description?: string,
  image?: string | null,
  creatorId?: string,
  categories?: Array< string > | null,
  posts?:  Array<Post | null > | null,
  players?:  Array<User | null > | null,
  createdAt?: string,
  updatedAt?: string,
};

export type Post = {
  __typename: "Post",
  id?: string,
  creatorId?: string,
  name?: string,
  displayName?: string,
  body?: string,
  round?: number,
  links?:  Array<Post | null > | null,
  image?: string | null,
  createdAt?: string,
  updatedAt?: string,
};

export type User = {
  __typename: "User",
  id?: string,
  secruityLevel?: number,
  image?: string | null,
  playerName?: string,
  characterName?: string,
  posts?:  Array<Post | null > | null,
  games?:  Array<Game | null > | null,
  createdAt?: string,
  updatedAt?: string,
};

export type UpdateGameInput = {
  id: string,
  title?: string | null,
  description?: string | null,
  image?: string | null,
  creatorId?: string | null,
  categories?: Array< string > | null,
};

export type DeleteGameInput = {
  id?: string | null,
};

export type CreatePostInput = {
  id?: string | null,
  creatorId: string,
  name: string,
  displayName: string,
  body: string,
  round: number,
  image?: string | null,
};

export type ModelPostConditionInput = {
  creatorId?: ModelStringInput | null,
  name?: ModelStringInput | null,
  displayName?: ModelStringInput | null,
  body?: ModelStringInput | null,
  round?: ModelIntInput | null,
  image?: ModelStringInput | null,
  and?: Array< ModelPostConditionInput | null > | null,
  or?: Array< ModelPostConditionInput | null > | null,
  not?: ModelPostConditionInput | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdatePostInput = {
  id: string,
  creatorId?: string | null,
  name?: string | null,
  displayName?: string | null,
  body?: string | null,
  round?: number | null,
  image?: string | null,
};

export type DeletePostInput = {
  id?: string | null,
};

export type CreateUserInput = {
  id?: string | null,
  secruityLevel: number,
  image?: string | null,
  playerName: string,
  characterName: string,
};

export type ModelUserConditionInput = {
  secruityLevel?: ModelIntInput | null,
  image?: ModelStringInput | null,
  playerName?: ModelStringInput | null,
  characterName?: ModelStringInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type UpdateUserInput = {
  id: string,
  secruityLevel?: number | null,
  image?: string | null,
  playerName?: string | null,
  characterName?: string | null,
};

export type DeleteUserInput = {
  id?: string | null,
};

export type ModelGameFilterInput = {
  id?: ModelIDInput | null,
  title?: ModelStringInput | null,
  description?: ModelStringInput | null,
  image?: ModelStringInput | null,
  creatorId?: ModelStringInput | null,
  categories?: ModelStringInput | null,
  and?: Array< ModelGameFilterInput | null > | null,
  or?: Array< ModelGameFilterInput | null > | null,
  not?: ModelGameFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelGameConnection = {
  __typename: "ModelGameConnection",
  items?:  Array<Game | null > | null,
  nextToken?: string | null,
};

export type ModelPostFilterInput = {
  id?: ModelIDInput | null,
  creatorId?: ModelStringInput | null,
  name?: ModelStringInput | null,
  displayName?: ModelStringInput | null,
  body?: ModelStringInput | null,
  round?: ModelIntInput | null,
  image?: ModelStringInput | null,
  and?: Array< ModelPostFilterInput | null > | null,
  or?: Array< ModelPostFilterInput | null > | null,
  not?: ModelPostFilterInput | null,
};

export type ModelPostConnection = {
  __typename: "ModelPostConnection",
  items?:  Array<Post | null > | null,
  nextToken?: string | null,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  secruityLevel?: ModelIntInput | null,
  image?: ModelStringInput | null,
  playerName?: ModelStringInput | null,
  characterName?: ModelStringInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelUserConnection = {
  __typename: "ModelUserConnection",
  items?:  Array<User | null > | null,
  nextToken?: string | null,
};

export type CreateGameMutationVariables = {
  input?: CreateGameInput,
  condition?: ModelGameConditionInput | null,
};

export type CreateGameMutation = {
  createGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateGameMutationVariables = {
  input?: UpdateGameInput,
  condition?: ModelGameConditionInput | null,
};

export type UpdateGameMutation = {
  updateGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteGameMutationVariables = {
  input?: DeleteGameInput,
  condition?: ModelGameConditionInput | null,
};

export type DeleteGameMutation = {
  deleteGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreatePostMutationVariables = {
  input?: CreatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type CreatePostMutation = {
  createPost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdatePostMutationVariables = {
  input?: UpdatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type UpdatePostMutation = {
  updatePost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeletePostMutationVariables = {
  input?: DeletePostInput,
  condition?: ModelPostConditionInput | null,
};

export type DeletePostMutation = {
  deletePost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateUserMutationVariables = {
  input?: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateUserMutationVariables = {
  input?: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteUserMutationVariables = {
  input?: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetGameQueryVariables = {
  id?: string,
};

export type GetGameQuery = {
  getGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListGamesQueryVariables = {
  filter?: ModelGameFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListGamesQuery = {
  listGames?:  {
    __typename: "ModelGameConnection",
    items?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetPostQueryVariables = {
  id?: string,
};

export type GetPostQuery = {
  getPost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListPostsQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPostsQuery = {
  listPosts?:  {
    __typename: "ModelPostConnection",
    items?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetUserQueryVariables = {
  id?: string,
};

export type GetUserQuery = {
  getUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers?:  {
    __typename: "ModelUserConnection",
    items?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateGameSubscription = {
  onCreateGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateGameSubscription = {
  onUpdateGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteGameSubscription = {
  onDeleteGame?:  {
    __typename: "Game",
    id: string,
    title: string,
    description: string,
    image?: string | null,
    creatorId: string,
    categories?: Array< string > | null,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    players?:  Array< {
      __typename: "User",
      id: string,
      secruityLevel: number,
      image?: string | null,
      playerName: string,
      characterName: string,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      games?:  Array< {
        __typename: "Game",
        id: string,
        title: string,
        description: string,
        image?: string | null,
        creatorId: string,
        categories?: Array< string > | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreatePostSubscription = {
  onCreatePost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdatePostSubscription = {
  onUpdatePost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeletePostSubscription = {
  onDeletePost?:  {
    __typename: "Post",
    id: string,
    creatorId: string,
    name: string,
    displayName: string,
    body: string,
    round: number,
    links?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    image?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateUserSubscription = {
  onCreateUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser?:  {
    __typename: "User",
    id: string,
    secruityLevel: number,
    image?: string | null,
    playerName: string,
    characterName: string,
    posts?:  Array< {
      __typename: "Post",
      id: string,
      creatorId: string,
      name: string,
      displayName: string,
      body: string,
      round: number,
      links?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    games?:  Array< {
      __typename: "Game",
      id: string,
      title: string,
      description: string,
      image?: string | null,
      creatorId: string,
      categories?: Array< string > | null,
      posts?:  Array< {
        __typename: "Post",
        id: string,
        creatorId: string,
        name: string,
        displayName: string,
        body: string,
        round: number,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      players?:  Array< {
        __typename: "User",
        id: string,
        secruityLevel: number,
        image?: string | null,
        playerName: string,
        characterName: string,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
